version: "3.9"  # Use version 3.9 or higher for compatibility
services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher 
    ports:
    - "80:80"
    - "8443:443"
    restart: unless-stopped
    privileged: true

